### ISSUE TITLE
Occasional authentication errors

### ISSUE THREAD

**Issue by bsamsom** [jgr3go/node-wheniwork#2]
We have been using this for a long time and have an ongoing error that we have not been able to solve, Occasionally we get the below error that appears to be from the token expiring or getting dropped leading to authentication issues.

```
{ Error: 1000 - User login required for this resource.
     at request.catch.err (/app/node_modules/wheniwork/dist/wheniwork.js:49:19)
     at tryCatcher (/app/node_modules/request-promise/node_modules/bluebird/js/release/util.js:16:23)
     at Promise._settlePromiseFromHandler (/app/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:547:31)
     at Promise._settlePromise (/app/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:604:18)
     at Promise._settlePromise0 (/app/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:649:10)
     at Promise._settlePromises (/app/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:725:18)
     at _drainQueueStep (/app/node_modules/request-promise/node_modules/bluebird/js/release/async.js:93:12)
     at _drainQueue (/app/node_modules/request-promise/node_modules/bluebird/js/release/async.js:86:9)
     at Async._drainQueues (/app/node_modules/request-promise/node_modules/bluebird/js/release/async.js:102:5)
     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/request-promise/node_modules/bluebird/js/release/async.js:1
     at runCallback (timers.js:705:18)
     at tryOnImmediate (timers.js:676:5)
     at processImmediate (timers.js:658:5)
     at process.topLevelDomainCallback (domain.js:120:23) status: 401, code: 1000 }
```
     
Reading the https://apidocs.wheniwork.com/external/index.html and running the curl provides no TTL on the token so i'm not sure whats happening here if the token has a hidden expiry or if its getting dropped somewhere.
```
curl -X POST \
  https://api.login.wheniwork.com/login \
  -H 'W-Key: <INSERT_DEVELOPER_KEY_HERE>' \
  -H 'content-type: application/json' \
  -d '{"email":"<INSERT_USERNAME_HERE>","password":"<INSERT_PASSWORD_HERE>"}'
```

**Comment by jgr3go** [comment]
Yeah, what I've found is WIW made a change in the last couple months to reduce the token expiration from (seemingly) forever to expire after a week.  For any apps I have using this library that run longer than a week, I have a timer that just reinstantiates the reference to the class so it gets a new token.  The correct fix would be for this class to use the RefreshToken endpoint they have so any consumers don't have to worry about it.

**Comment by bsamsom** [comment]
Thank you for the information, ill add a cron to the app to refresh the token.
